### ISSUE TITLE
plotly.js with uglifier and webpacker

### ISSUE THREAD

**Issue by erick-umc** [plotly/plotly.js#5022]
Hello, 

I'm currently using plotly.js on my react & rails app. While I'm in development mode plotly works very well, however after I deploy to my production I get the following error on the app: 

```
fromRequireContextWithGlobalFallback.js:21 TypeError: l is not a function
    at plotly.js:1088
    at plotly.js:1051
    at Object.55.d3-array (plotly.js:1050)
    at o (plotly.js:48)
    at plotly.js:50
    at Object.1131.../../components/color (plotly.js:220890)
    at o (plotly.js:48)
    at plotly.js:50
    at Object.1130.../../components/color (plotly.js:220515)
    at o (plotly.js:48)
```

I'm guessing that plotly is breaking when rake assets:precompile ENV=production is ran. This command compiles my javascript using webpacker and then concatenates them and compresses them using uglifier.  

Here is the my webpacker.yml configuration: 

```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  #webpack_compile_output: true

  resolved_paths: []
  cache_manifest: false
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .tsx
    - .ts
    - .jsx
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default
  #public_output_path: assets/packs

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```

If you have any idea on how to solve this error, let me know.

Thank you, 
Erick
