### ISSUE TITLE
Ploty.js in Shadow DOM did not handle CSS transform correctly

### ISSUE THREAD

**Issue by OpportunityLiu** [plotly/plotly.js#5760]
A chart in shadow DOM https://codepen.io/opportunityliu/pen/poeXjmr
A chart out of shadow DOM https://codepen.io/opportunityliu/pen/Rwpzrww

They are both applied same CSS transform
```css
#plot {
  display: block;
  width: 50%;
  margin-left: 50%;
  transform: scale(2, 1);
  transform-origin: right;
}
```
and looks similar
![image](https://user-images.githubusercontent.com/13471233/123033838-f9cafc80-d41a-11eb-9fbe-3feb15b1366d.png)

But when interacting with the plot, seems the plot in shadow DOM has wrong coordinate of mouse events.
![动画](https://user-images.githubusercontent.com/13471233/123034398-013ed580-d41c-11eb-9ba0-d370b99fc576.gif)
