### ISSUE TITLE
TailwindCSS breaks Plotly modebar layout

### ISSUE THREAD

**Issue by wuyuanyi135** [plotly/plotly.js#5828]
When using Plotly together with TailWindCSS I noticed that the mode bar's layout is not correct:
![image](https://user-images.githubusercontent.com/11760870/125908089-893778f3-9374-4c8c-902b-ca37cd084a25.png)
Here is the [codepen](https://codepen.io/wuyuanyi135/pen/KKmWOgO) for reproducing this error.

I could confirm this was caused by the following rule that override the `display` property of `.main-svg`.
```css
img, svg, video, canvas, audio, iframe, embed, object {
    display: block;
    vertical-align: middle;
}
```

I could fix this by adding this to override the CSS normalization behavior. 
```css
svg {
    display: inherit;
}
```

I noticed that the `display` property was `block` anyway. I don't understand how this inconsistency is caused. Do you think this is a bug?

**Comment by tashburn** [comment]
+1

**Comment by tashburn** [comment]
I have this issue too, but the `svg{display:inherit;}` does not fix it for me.

**Comment by brendanmatkin** [comment]
This is a fix:
```css
.js-plotly-plot .plotly .modebar svg {
	display: inline;
}
```

or in svelte (which I'm using):
```css
:global(.js-plotly-plot .plotly .modebar svg) {
	display: inline;
}
```

this is due to tailwind using css remedy style reset. The discussion about changing svg to block is [here](https://github.com/jensimmons/cssremedy/issues/14).
