### ISSUE TITLE
Citation file for Plotly.js

### ISSUE THREAD

**Issue by Coding-with-Adam** [plotly/plotly.js#7223]
I'd like to propose that we create a formal `citation.cff` file for plotly.js that we can refer people to when they want to cite Plotly.
There are at least two pending actions:
1. If we need a [doi](https://ask.library.uic.edu/faq/345899) (third line from the bottom), someone with admin rights will have to create a [zenodo account](https://zenodo.org/) and upload the file. I'm happy to help if I am granted the rights. 
2. we should also see if we can write some script that can automatically update the plotly.js version (fourth line from the bottom) every time a new version comes out.

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Johnson"
  given-names: "Alex"
  Plotly: "https://github.com/alexcjohnson"
- family-names: "Tétreault-Pinard"
  given-names: "Étienne"
  Plotly: "https://github.com/etpinard"
- family-names: "Samimi"
  given-names: "Mojtaba"
  Plotly: "https://github.com/archmoj"
title: "Open-source charting library behind Plotly"
version: 2.35.2
doi: 10.5281/zenodo.1234sample (Plotly admin will have to create this on zenodo)
date-released: 2015-11-17
url: "https://github.com/plotly/plotly.js"
```
