### ISSUE TITLE
Double click on "scattergl" plot makes panning option not to work properly

### ISSUE THREAD

**Issue by ifll** [plotly/plotly.js#744]
When clicking the panning option of the menubar of the plot it is possible to pan the plot. Once you doubleclick the plot, the panning option is still available but the panning range is rescricted to a small distance, which makes that for covering a large paning you have to click -> pan -> click again -> pan again -> click again....

Clicking again the panning option of the menubar resets the panning and it is available to pan normally again.

It is possible to reproduce this problem here:
http://codepen.io/etpinard/pen/XXrzBe

**Comment by etpinard** [comment]
Part of the known gl2d limitations https://github.com/plotly/plotly.js/issues/130

**Comment by etpinard** [comment]
@dfcreative might be interested in this issue too ...

**Comment by dfcreative** [comment]
Not sure what it is caused by, but adding
```css
.plotly .gtitle {
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
}
```
solves the issue.
